# Edit the template parameters below to see how they will render in the scaffolder form UI
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: chatbot-rag-private-docs-template
  title: Secured Chatbot Chatbot assistant using private documents with RAG
  description: Creates a secured python chatbot which enables you to ingest private documents for RAG
  tags:
    - recommended
    - java
    - python
    - ai
    - rhoai
    - rag
    - rhtap
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Choose a model
      required:
        - model
      properties:
        model:
          title: model
          type: string
          default: ibm-granite/granite-3.2-8b-instruct
          enum:
          - meta-llama/Llama-3.2-3B-Instruct
          - ibm-granite/granite-3.2-8b-instruct
          description: choose your LLM model
        enbableGPUSupport:
          title: Enable GPU Support 
          type: boolean
          ui:widget: radio
          description: defaults to cpu
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{parameters.name}}
